server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
spring:
  application:
    name: yyw-crowd-order
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
  main:
    allow-bean-definition-overriding: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000